### ISSUE TITLE
Standalone programs do not maintain their environment

### ISSUE THREAD

**Issue by 414owen** [byxor/limp#6]
For example, if I run a program like this:

```
(define a 3)
a
```

It will not print `3`, it will print `None`. This is because the environment isn't maintained like it is in a REPL, the define is taken as the whole program.

The obvious solution is to wrap the entire program in a `do` block, either in text or by adding the tokens manually.

**Comment by byxor** [comment]
Yes, this was how I planned to handle loading code from files. Implicitly wrapping them in `do`.

**Comment by byxor** [comment]
Note:

```
(define a 3)
a
```

is no longer a valid code snippet as of version `0.9.0`.

* `define` has been removed from the language and I'm thinking of a cleaner/less-stateful alternative.
* Check #22 for more info.
